dao6 done
less08/dao3 pull request #4
Opened 2021-01-18 19:05 UTC by less08

2021-01-18 20:01 UTC, Max-Pochepets requested changes

2021-01-18 20:01 UTC, Max-Pochepets commented on src/main/java/core/dao/jdbc/CarDaoJdbcImpl.java
> +                car = createCar(resultSet);
if I'm not mistaken, `createCar()` returns a car without assigned drivers

2021-01-18 20:01 UTC, Max-Pochepets commented on src/main/java/core/dao/jdbc/CarDaoJdbcImpl.java
> +                carList.add(createCar(resultSet));
same

2021-01-18 20:01 UTC, Max-Pochepets commented on src/main/java/core/dao/jdbc/CarDaoJdbcImpl.java
> +            //update car
for me these comments are OK, but statements names speak for themselves. you can delete comments and leave line separations if you want to highlight the stages

2021-01-18 20:01 UTC, Max-Pochepets commented on src/main/java/core/dao/jdbc/CarDaoJdbcImpl.java
> +            throw new DataProcessingException("Can't update car ", e);
which car?

2021-01-18 20:01 UTC, Max-Pochepets commented on src/main/java/core/dao/jdbc/CarDaoJdbcImpl.java
> +                + "d.driver_id, d.driver_name, d.licence_number FROM cars "
```suggestion
                + "d.driver_id, d.driver_name, d.licence_number FROM cars c"
```
you should either use alias everywhere or don't use it at all

2021-01-18 20:01 UTC, Max-Pochepets commented on src/main/java/core/dao/jdbc/CarDaoJdbcImpl.java
> +                 PreparedStatement getFilteredStmt = connection.prepareStatement(query)) {
```suggestion
                 PreparedStatement getFilteredStatement = connection.prepareStatement(query)) {
```
let's use full names, it won't get much of your time considering modern technologies

2021-01-19 10:25 UTC, Max-Pochepets approved these changes

2021-01-19 11:22 UTC, dmytro-hryhoruk approved these changes

2021-01-19 11:22 UTC, dmytro-hryhoruk commented on src/main/java/core/dao/jdbc/CarDaoJdbcImpl.java
> +            return Optional.ofNullable(car);
```suggestion
            while (resultSet.next()) {
                return Optional.of(createCar(connection, resultSet));
            }
            return Optional.empty();
```

2021-01-19 11:22 UTC, dmytro-hryhoruk commented on src/main/java/core/dao/jdbc/CarDaoJdbcImpl.java
> +                + "WHERE c.deleted = FALSE AND d.id=?";
check drivers on deleted too

2021-01-19 11:32 UTC, merged